Feature/otimizacoes e renderizacao de repositorios
cherryramatisdev/4noobs_tracker pull request #21
Opened 2023-09-03 21:45 UTC by Nandosts

Closes #10  (eu acredito kk)

## Mudanças Propostas

### Problema

O pedido original foi de implementar uma stream de dados, para poder carregar gradualmente os repositórios e evitar o erro da tela piscando branca antes de carregar

### Soluções Propostas

Como alternativa, propomos as seguintes mudanças:

1. **Paginação Inteligente:**
   - Usei uma gem de paginação para carregar de 10 em 10 itens, o que resolve o problema de renderizar todos de uma só vez (Porém o javascript se encarrega de fazer com que todos esses itens sejam dispostos em uma só tela, ao invés de várias páginas);

2. **Tela de Loading:**
   - Criei uma tela de loading por padrão, para ter algo na tela quando tiver algo pesado ao invés de piscar em branco;

3. **Otimização do UnoCSS:**
   - Movi o CDN do UnoCSS para um arquivo importável em nosso projeto. Isso significa que ele agora está presente em um arquivo estático, eliminando a necessidade de ser baixado dinamicamente através da tag `<script>`. A ideia é acelerar o carregamento, mas também melhora a estabilidade geral da aplicação.

### Observações Importantes

- **Aprimoramentos Futuros:** O Loading pode ser melhorado ainda, com algum método global que faça com que ele seja adicionado ou retirado em tela conforme necessidade;
- **CDN do UnoCSS:** O CDN do UnoCSS, no momento de criação desta PR, está todo contido em um arquivo javascript, então ele não vai receber atualizações futuras dessa forma. Pode haver alguma outra solução para baixar esse arquivo quando houver alguma alteração, ou caso tenha a necessidade de atualizar terá de ser feito manualmente;

Agradeço qualquer feedback possível, e espero que isso ajude na solução final kk

2023-09-03 22:56 UTC, cherryramatisdev requested changes

2023-09-03 22:56 UTC, cherryramatisdev commented on app/assets/stylesheets/application.css
> +  z-index: 9999;
Não precisamos utilizar algo tão brusco, desde que tenhamos um controle dos z-index podemos utilizar algo como `100` pra um alerta

2023-09-03 22:56 UTC, cherryramatisdev commented on app/javascript/application.js
> +});
Move isso para um arquivo especifico como `app/javascript/pagination_loader.js`

2023-09-03 22:56 UTC, cherryramatisdev commented on app/views/layouts/application.html.erb
> +      <div class="spinner"></div>
```suggestion
      <div class="spinner" />
```

2023-09-03 22:56 UTC, cherryramatisdev commented on app/views/layouts/application.html.erb
> +    <div class="loading-spinner" id="loading-spinner">
Ao inves de usar uma classe e um id, podemos deixar apenas o id e estilizar no css utilizando `#loading-spinner`

Visto que um loading-spinner sempre vai ter o mesmo estilo na nossa aplicação hoje

2023-09-03 22:56 UTC, cherryramatisdev commented on app/views/layouts/application.html.erb
> +
Seria legal mover isso para uma partial localizada em `app/views/layouts/_spinner.html.erb` e usar nessa view com `<%= render 'spinner' %>`

2023-09-03 22:56 UTC, cherryramatisdev commented
Primeiramente parabéns pela PR! ficou incrível e acredito que resolve sim o nosso problema descrito na issue

Deixei alguns comentarios para qualidade geral do código, qualquer duvida estou disponivel

2023-09-04 00:16 UTC, Nandosts commented
> Primeiramente parabéns pela PR! ficou incrível e acredito que resolve sim o nosso problema descrito na issue
> 
> Deixei alguns comentarios para qualidade geral do código, qualquer duvida estou disponivel

Muuito obrigado por mais esses feedbacks
Fiz as alterações sugeridas, coloquei o spinner em uma partial

De quebra, na verdade, acabei descobrindo que também tinha uma classe do unocss chamada "loading-spinner", tava meio que agindo junto aí kk
Mas agora resolvido, coloquei o css em um arquivo separado também, para organizar passo a passo

2023-09-04 10:07 UTC, cherryramatisdev commented
> > Primeiramente parabéns pela PR! ficou incrível e acredito que resolve sim o nosso problema descrito na issue
> > Deixei alguns comentarios para qualidade geral do código, qualquer duvida estou disponivel
> 
> Muuito obrigado por mais esses feedbacks Fiz as alterações sugeridas, coloquei o spinner em uma partial
> 
> De quebra, na verdade, acabei descobrindo que também tinha uma classe do unocss chamada "loading-spinner", tava meio que agindo junto aí kk Mas agora resolvido, coloquei o css em um arquivo separado também, para organizar passo a passo

boa maravilha

2023-09-04 10:08 UTC, cherryramatisdev approved these changes
LGTM

2023-09-04 10:08 UTC, merged